// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VariableCompensation.Infrastructure.Persistence;

#nullable disable

namespace VariableCompensation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920140542_DropMeasureDescriptions")]
    partial class DropMeasureDescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Compensation.VariableCompensationEvaluationLink", b =>
                {
                    b.Property<long>("ResultId")
                        .HasColumnType("bigint");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.HasKey("ResultId", "EvaluationId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("variable_compensation_evaluation_links", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Compensation.VariableCompensationParameters", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AcceptablePerformanceRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<bool>("AllowNegativeVariable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("DependencyWeight")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("Exponent")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonetaryPool")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UpperLimitCoefficient")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationUnitId", "Year")
                        .IsUnique();

                    b.ToTable("variable_compensation_parameters", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Compensation.VariableCompensationResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Aq")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CompensationPercent")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<decimal>("CompensationWithoutSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FormulaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("GoalsAverage")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MeasuresAverage")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("MonthlyCompensation")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NetCompensation")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NormalizedPoints")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("NormalizedZScore")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("OverallAverage")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<long>("ParametersId")
                        .HasColumnType("bigint");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuarterlyCompensation")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SalaryPointsValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.Property<decimal>("ZScore")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ParametersId");

                    b.HasIndex("EmployeeId", "ParametersId", "Year")
                        .IsUnique();

                    b.ToTable("variable_compensation_results", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.Evaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConditionsFulfilled")
                        .HasColumnType("boolean");

                    b.Property<string>("ConditionsNotMetComment")
                        .HasColumnType("text");

                    b.Property<string>("ControllerComment")
                        .HasColumnType("text");

                    b.Property<long?>("ControllerEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ControllerViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConversationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DescriptiveRatingId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("EvaluatorComment")
                        .HasColumnType("text");

                    b.Property<long>("EvaluatorEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ExcludedFromCompensation")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("GoalsAverage")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal?>("MeasuresAverage")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal?>("OverallAverage")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<byte>("Quarter")
                        .HasColumnType("smallint");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ControllerEmployeeId");

                    b.HasIndex("DescriptiveRatingId");

                    b.HasIndex("EvaluatorEmployeeId");

                    b.HasIndex("Status");

                    b.HasIndex("Year", "Quarter");

                    b.HasIndex("EmployeeId", "Year", "Quarter")
                        .IsUnique();

                    b.ToTable("evaluations", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("evaluation_conditions", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationCriterion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("evaluation_criteria", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationGoal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<long>("RatingLevelId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("RatingLevelId");

                    b.ToTable("evaluation_goals", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationMeasure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<long>("MeasureTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("RatingComment")
                        .HasColumnType("text");

                    b.Property<long>("RatingLevelId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("MeasureTypeId");

                    b.HasIndex("RatingLevelId");

                    b.ToTable("evaluation_measures", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ChangedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("evaluation_status_history", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationTraining", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DevelopmentDescription")
                        .HasColumnType("text");

                    b.Property<long>("EvaluationId")
                        .HasColumnType("bigint");

                    b.Property<string>("EvaluatorComment")
                        .HasColumnType("text");

                    b.Property<string>("KnowledgeDescription")
                        .HasColumnType("text");

                    b.Property<string>("TrainingDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.ToTable("evaluation_trainings", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Hr.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EducationLevelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EvaluatorEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("HiredAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("JobPositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("EvaluatorEmployeeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Hr.EmployeeSalary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("EncryptedSalaryPerPoint")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "EffectiveFrom");

                    b.ToTable("employee_salaries", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Hr.EvaluatorSettings", b =>
                {
                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ControllerEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PercentDoesNotMeet")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PercentExceeds")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PercentGood")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PercentMeets")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ThresholdDoesNotMeet")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ThresholdExceeds")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ThresholdGood")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ThresholdMeets")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ControllerEmployeeId");

                    b.ToTable("evaluator_settings", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Identity.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.DescriptiveRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxAverage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinAverage")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RecommendedShare")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("descriptive_ratings", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.EducationLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("education_levels", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.JobPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("job_positions", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.MeasureType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("measure_types", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.OrganizationUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("organization_units", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.RatingLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("rating_levels", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Compensation.VariableCompensationEvaluationLink", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Evaluation.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Compensation.VariableCompensationResult", "Result")
                        .WithMany("EvaluationLinks")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Compensation.VariableCompensationParameters", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Lookup.OrganizationUnit", "OrganizationUnit")
                        .WithMany("CompensationParameters")
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationUnit");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Compensation.VariableCompensationResult", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Hr.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Compensation.VariableCompensationParameters", "Parameters")
                        .WithMany("Results")
                        .HasForeignKey("ParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.Evaluation", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Hr.Employee", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VariableCompensation.Domain.Entities.Lookup.DescriptiveRating", "DescriptiveRating")
                        .WithMany()
                        .HasForeignKey("DescriptiveRatingId");

                    b.HasOne("VariableCompensation.Domain.Entities.Hr.Employee", "Employee")
                        .WithMany("Evaluations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Hr.Employee", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("DescriptiveRating");

                    b.Navigation("Employee");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationCondition", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Evaluation.Evaluation", "Evaluation")
                        .WithMany("Conditions")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationCriterion", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Evaluation.Evaluation", "Evaluation")
                        .WithMany("Criteria")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationGoal", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Evaluation.Evaluation", "Evaluation")
                        .WithMany("Goals")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Lookup.RatingLevel", "RatingLevel")
                        .WithMany()
                        .HasForeignKey("RatingLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("RatingLevel");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationMeasure", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Evaluation.Evaluation", "Evaluation")
                        .WithMany("Measures")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Lookup.MeasureType", "MeasureType")
                        .WithMany()
                        .HasForeignKey("MeasureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Lookup.RatingLevel", "RatingLevel")
                        .WithMany()
                        .HasForeignKey("RatingLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("MeasureType");

                    b.Navigation("RatingLevel");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationStatusHistory", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Evaluation.Evaluation", "Evaluation")
                        .WithMany("StatusHistory")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.EvaluationTraining", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Evaluation.Evaluation", "Evaluation")
                        .WithOne("Training")
                        .HasForeignKey("VariableCompensation.Domain.Entities.Evaluation.EvaluationTraining", "EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Hr.Employee", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Lookup.EducationLevel", "EducationLevel")
                        .WithMany("Employees")
                        .HasForeignKey("EducationLevelId");

                    b.HasOne("VariableCompensation.Domain.Entities.Hr.Employee", "Evaluator")
                        .WithMany("Subordinates")
                        .HasForeignKey("EvaluatorEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VariableCompensation.Domain.Entities.Lookup.JobPosition", "JobPosition")
                        .WithMany("Employees")
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Lookup.OrganizationUnit", "OrganizationUnit")
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Identity.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("VariableCompensation.Domain.Entities.Hr.Employee", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EducationLevel");

                    b.Navigation("Evaluator");

                    b.Navigation("JobPosition");

                    b.Navigation("OrganizationUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Hr.EmployeeSalary", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Hr.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Hr.EvaluatorSettings", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Hr.Employee", "Controller")
                        .WithMany()
                        .HasForeignKey("ControllerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Hr.Employee", "Employee")
                        .WithOne("EvaluatorSettings")
                        .HasForeignKey("VariableCompensation.Domain.Entities.Hr.EvaluatorSettings", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Identity.UserRole", b =>
                {
                    b.HasOne("VariableCompensation.Domain.Entities.Lookup.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VariableCompensation.Domain.Entities.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Compensation.VariableCompensationParameters", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Compensation.VariableCompensationResult", b =>
                {
                    b.Navigation("EvaluationLinks");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Evaluation.Evaluation", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Criteria");

                    b.Navigation("Goals");

                    b.Navigation("Measures");

                    b.Navigation("StatusHistory");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Hr.Employee", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("EvaluatorSettings");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.EducationLevel", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.JobPosition", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.OrganizationUnit", b =>
                {
                    b.Navigation("CompensationParameters");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("VariableCompensation.Domain.Entities.Lookup.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
