// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VariableCompensation.Infrastructure.Persistence;

#nullable disable

namespace VariableCompensation.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260702180000_AddEvaluationTrainingEvaluatorComment")]
public partial class AddEvaluationTrainingEvaluatorComment
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
